version: "3.9"

services:
  mountebank:
    image: bbyars/mountebank:2.9.1
    ports:
      - "4040:4040"
      - "4545:4545"
      - "2525:2525"
    volumes:
      - ./imposters:/imposters
    command: --configfile /imposters/imposters.ejs --debug
